.PHONY: all clean cleanall

all:
	make -C ./http_pattern_matching
	make -C ./dump_jpeg
	make -C ./protocol_identification
 
clean: 
	make -C ./http_pattern_matching clean
	make -C ./dump_jpeg clean
	make -C ./protocol_identification clean
cleanall:
	make -C ./http_pattern_matching cleanall
	make -C ./dump_jpeg cleanall
	make -C ./protocol_identification cleanall

