#include <peafowl/peafowl.h>

char const* pfwl_fields_l7_names[] = {
  "SIP_FIRST", 
  "SIP_REQUEST_URI", 
  "SIP_METHOD", 
  "SIP_CALLID", 
  "SIP_REASON", 
  "SIP_RTCPXR_CALLID", 
  "SIP_CSEQ", 
  "SIP_CSEQ_METHOD_STRING", 
  "SIP_VIA", 
  "SIP_CONTACT_URI", 
  "SIP_RURI_USER", 
  "SIP_RURI_DOMAIN", 
  "SIP_FROM_USER", 
  "SIP_FROM_DOMAIN", 
  "SIP_TO_USER", 
  "SIP_TO_DOMAIN", 
  "SIP_PAI_USER", 
  "SIP_PAI_DOMAIN", 
  "SIP_PID_URI", 
  "SIP_FROM_URI", 
  "SIP_TO_URI", 
  "SIP_RURI_URI", 
  "SIP_TO_TAG", 
  "SIP_FROM_TAG", 
  "SIP_LAST", 
  "DNS_FIRST", 
  "DNS_NAME_SRV", 
  "DNS_NS_IP_1", 
  "DNS_NS_IP_2", 
  "DNS_AUTH_SRV", 
  "DNS_LAST", 
  "SSL_FIRST", 
  "SSL_CERTIFICATE", 
  "SSL_LAST", 
  "HTTP_FIRST", 
  "HTTP_VERSION_MAJOR", 
  "HTTP_VERSION_MINOR", 
  "HTTP_METHOD", 
  "HTTP_STATUS_CODE", 
  "HTTP_MSG_TYPE", 
  "HTTP_BODY", 
  "HTTP_URL", 
  "HTTP_HEADERS", 
  "HTTP_LAST", 
  "RTP_FIRST", 
  "RTP_PTYPE", 
  "RTP_SEQNUM", 
  "RTP_TIMESTP", 
  "RTP_SSRC", 
  "RTP_LAST", 
  "NUM"
};

const char* pfwl_get_L7_field_name(pfwl_field_id_t field){
   return pfwl_fields_l7_names[field];
}
